name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cache-npm-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            cache-npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
            cache-npm-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
